#!/bin/sh

echo "Running tests before push..."

./.venv/Scripts/python.exe -m pytest

if [ $? -ne 0 ]; then
    echo "Tests failed. Push cancelled."
    exit 1
fi

echo "All tests passed. Continuing push."
exit 0